config/routes.rb
Rails.application.routes.draw do

  resources :transactions, only: [:index]

  root to: 'home#index'

  devise_for :giftcards, controllers: {
    sessions: 'giftcards/sessions'
  }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/giftcard.rb
class Giftcard < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :number, presence: true, uniqueness: true, length: { minimum: 16, maximum: 16 }

  def email_required?
    false
  end

  def will_save_change_to_email?
    false
  end

  def balance(transactions)
    transactions.map {|transaction| transaction["transaction_value"]}.reduce(:+)
  end

end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :giftcard
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    transactions_path
  end
end

app/controllers/giftcards/sessions_controller.rb
# frozen_string_literal: true

class Giftcards::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:number])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  before_action :authenticate_giftcard!

  def index
    client = TransactionService::Fetch.new
    client.call
    @transactions = client.transactions
    @balance = current_giftcard.balance(@transactions)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <div class="divao">
    <div class="card-container">
      <img
        src="https://www.brides.com/thmb/I2wQp4Dpnv8uO7CWhFivAyG5Lys=/1425x0/filters:no_upscale():max_bytes(200000):strip_icc():format(webp)/sq-f1e8951c35014091a65b673fbb5ae7a4.jpg"
        alt="Foto de festa de casamento"
      />
      <div class="container__text">
          <h1>Parabens pelo seu casamento!!!</h1>
          <h3 class="punch-line">Agora é hora de aproveitar os seus presentes</h3>
          <button class="btn">
            <%= link_to "Ver o meu giftcard", new_giftcard_session_path, class: "link" %>
          </button>
      </div>
    </div>
  </div>
</html>

app/views/layouts/_footer.html.erb
<footer class="footer-distributed">
  <div class="footer-left">
      <p class="footer-links">
        <a href="#"><%= link_to "Home", root_path %></a>
        ·
        <a href="#">Sobre</a>
        ·
        <a href="#">Faq</a>
        ·
        <a href="#">Contatos</a>
      </p>
    </div>

    <div class="footer-center"></div>

  <div class="footer-right">

    <p class="footer-company-about">
      <span>Sobre a Todo</span>
      Varias empresas já usam nossos giftcards para presentes e listas.
    </p>

    <div class="footer-icons">
      <a href="#"><i class="fa fa-facebook"></i></a>
      <a href="#"><i class="fa fa-twitter"></i></a>
      <a href="#"><i class="fa fa-linkedin"></i></a>
      <a href="#"><i class="fa fa-github"></i></a>
    </div>

  </div>
</footer>

app/views/layouts/_navbar.html.erb
<div class="nav">
  <div class="nav-header">
    <div class="nav-title">
      Todo
    </div>
  </div>
  <div class="nav-btn">
    <label for="nav-check">
      <span></span>
      <span></span>
      <span></span>
    </label>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioTodoincomm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/transactions/index.html.erb
<div class="giftcard-container">
  <div class="giftcard-infos">

    <h1>Meu Giftcard</h1>

    <div class="card-giftcard">
      <img class="giftcard-bg" src="https://cdn.shopify.com/s/files/1/0088/8589/5225/products/fee525424486bc85c5d5d1bf1c0f05a7_800x.jpg?v=1591457014" alt="">
    </div>

    <div class="infos">
      <h3>Informaçōes</h3>
      <ul>
        <li>Numero do cartão: <%= current_giftcard.number %></li>
        <li>Mensagem: <%= current_giftcard.message %></li>
        <li>Saldo: <%= @balance %></li>
        <li>Validade: <%= current_giftcard.expiration.strftime('%m/%y') %></li>
      </ul>
    </div>

  </div>
  <div class="transaction-infos">
    <h1>Minhas transaçoes</h1>
    <table class="customTable">
      <thead>
        <tr>
          <th>Tipo</th>
          <th>Data</th>
          <th>Valor</th>
          <th>Identificacao</th>
        </tr>
      </thead>
      <tbody>
      <% @transactions.each do |transaction| %>
        <tr>
          <td><%= transaction["transaction_type"] %></td>
          <td><%= transaction["transaction_value"] %></td>
          <td><%= transaction["transaction_date"] %></td>
          <td><%= transaction["store_identification"] %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>